const SO_DRAFT = '01'
const SO_SUBMIT_REVIEW = '02-04'
const SO_SUBMIT_REVIEW_APPROVE = '02-03'
const SO_FOR_REVIEW = '02'
const SO_REVIEW = '03'
const SO_APPROVE = '04'
const SO_PRINTING = '01-04'
const SO_PRINTED = '05'
const SO_APP_PRESIDENT = '06'
const SO_RETURNED_BY_REVIEW = '01-R'
const SO_RETURNED_BY_APPROVED = '02-R'
const SO_CANCELLED = '00'

const PROP_CREATE = '01'
const PROP_SUBMIT_REVIEW = '02-04'
const PROP_SUBMIT_REVIEW_APPROVE = '02-03'
const PROP_REVIEW = '03'
const PROP_APPROVE = '04'
const PROP_PRINTING = '01-04'
const PROP_PRINTED = '05'
const PROP_RETURNED_BY_REVIEW = '01-R'
const PROP_RETURNED_BY_APPROVE = '02-R'
const PROP_CANCELED = '00'
const PROP_LOST = '06'
const PROP_WIN = '07'
const PROP_WITH_SO = '08'

const STAGE1 = 'S001'
const STAGE2 = 'S002'
const STAGE3 = 'S003'

module.exports = {
    SO_DRAFT,
    SO_SUBMIT_REVIEW,
    SO_SUBMIT_REVIEW_APPROVE,
    SO_FOR_REVIEW,
    SO_REVIEW,
    SO_APPROVE,
    SO_PRINTING,
    SO_PRINTED,
    SO_APP_PRESIDENT,
    SO_RETURNED_BY_REVIEW,
    SO_RETURNED_BY_APPROVED,
    SO_CANCELLED,
    STAGE1,
    STAGE2,
    STAGE3,
    PROP_CREATE,
    PROP_SUBMIT_REVIEW,
    PROP_SUBMIT_REVIEW_APPROVE,
    PROP_REVIEW,
    PROP_APPROVE,
    PROP_PRINTING,
    PROP_PRINTED,
    PROP_RETURNED_BY_REVIEW,
    PROP_RETURNED_BY_APPROVE,
    PROP_CANCELED,
    PROP_LOST,
    PROP_WIN,
    PROP_WITH_SO
}